# GitHub Actions workflow for deploying a static site to Azure Web App
name: Deploy static site to Azure Web App - mglobal

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Check out the code from your repository
      - uses: actions/checkout@v4

      # Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mglobal' # Your Azure Web App name
          slot-name: 'Production'
          package: . # Path to the static files (root of the repo or specify folder)
