name: Deploy Static App to Azure

on:
  push:
    branches:
      - master  # Replace 'main' with your branch name if different
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment (required for Azure Static Web Apps CLI)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # LTS version; adjust if necessary

    # Deploy to Azure Static Web Apps
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"                 # Root folder of your static files
        output_location: ""               # No build output folder for plain HTML/JS