# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mglobal

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
 build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"                 # Root folder of your static files
        output_location: ""               # No build output folder for plain HTML/JS
     

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  #   permissions:
  #     id-token: write #This is required for requesting the JWT

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app
      
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0DFF405E6EA74E8EBC9AC8FE3875C313 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_26F7D7F1891F4E4AB84C704BBDA23ED5 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_44D30DEBA58F4BDC9CBD152FA10DE925 }}

  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v3
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'mglobal'
  #         slot-name: 'Production'
  #         package: .
          